### ISSUE TITLE
Traning on OOD syntheses

### ISSUE THREAD

**Issue by liudakai2** [deeplearning-wisc/npos#8]
Hi, I'm very interested in your work. However, I am confused about how the OOD syntheses participate in the training process. According to your paper and code, OOD syntheses are only trained with the BCE loss on an extra MLP layer, while the ID classifier, i.e., the prototype vectors are not involved. 

Here raises a question: since the final OOD detection score is computed based on the similarity between image feature and prototype vectors, why don't you add some constraints on the similarities between OOD syntheses and prototype vectors directly? You instead choose a proxy loss on an extra MLP layer to optimize the parameters in ViT indirectly, which confused me a lot.

I will be appreciated it if you could give more insights.

**Comment by taoleitian** [comment]
Thanks for your interest in our work!

To answer your question, the reason we do not add direct constraints on the similarities between OOD syntheses and prototype vectors is that the prototype vectors are learned from the ID training data and may not be representative of OOD inputs. Therefore, it may not be appropriate to use the prototype vectors directly to constrain the OOD syntheses. Instead, we use the BCE loss on an extra MLP layer to train the OOD classifier, which indirectly optimizes the parameters in the visual transformer to improve its OOD detection performance.

Specifically, we add an extra MLP layer on top of the visual transformer to classify the input as ID or OOD. During training, we use the BCE loss to train the MLP layer to predict the correct label. The OOD syntheses are treated as OOD inputs and are used to augment the training data. Since the OOD classifier is trained on both ID and OOD data, it can learn to distinguish between them and improve the overall OOD detection performance of the visual transformer.
